### ISSUE TITLE
Implement Test cases 

### ISSUE THREAD

**Issue by michiboo** [JuliaClimate/CDSAPI.jl#12]

**Comment by juliohm** [comment]
Nice. What kinds of tests do you have in mind? Are you aware of how testing works in Julia?

Please let me know if you need some help in the process. All you need to do is add content to the `runtests.jl` file that already exists, and then run the tests locally in the package manager mode:

```
] test CDSAPI
```

on any environment that contains the `dev` version of the package.

**Comment by juliohm** [comment]
Here is a starter for the `runtests.jl` file:

```julia
using CDSAPI
using Test

datadir = joinpath(@__DIR__,"data")

# list of tests
testfiles = [
  "testset1.jl",
  "testset2.jl",
]

@testset "CDSAPI.jl" begin
  for testfile in testfiles
    include(testfile)
  end
end
```

You create a `data` folder inside the `test` folder and then write your tests in separate files like `testset1.jl`, `testset2.jl`. Each of these files has the following structure:

```julia
@testset "ERA5 data" begin
  # write some code and use @test to check for correctness
  @test 1 > 0
end
```

**Comment by michiboo** [comment]
@juliohm  I was planning to test py2ju & retrieve function but since JSON.parse will be used then no point to test it. 
But is it possible to test retrieve function since it need API key? Do you know if github action can encrypt the API key as env variable? 
Otherwise I think the test should be the example + assert that file is present + delete the file after.

**Comment by juliohm** [comment]
That is a good question @michiboo , I never played with tests that required API key. There is a probably a way but I am not aware of a solution. Perhaps we can find help on Slack or Zulip. I am also pinging GitHub action masters here to see if they can help (cc: @giordano @staticfloat @DilumAluthge)

**Comment by staticfloat** [comment]
If you search "github actions secret environment variables" you can find some good documentation on it: https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

**Comment by LakshyaKhatri** [comment]
By default in the `retrieve()` we have assumed that the `.cdsapirc` file resides in the home directory:
```julia
open(joinpath(homedir(),".cdsapirc")) do f
        for line in readlines(f)
            key, val = strip.(split(line,':', limit=2))
            creds[key] = val
        end
end
```

Where will that file go on GitHub? Is it something like setting up environments?

**Comment by LakshyaKhatri** [comment]
Hello @juliohm, I have written tests for testing `retrieve()` and `py2ju()`. Can you suggest me other things that need to be tested? what should I look for in the data?

**Comment by juliohm** [comment]
One thing we could do to improve the tests is use the `GRIB.jl` package in the tests to load the data from the `test/data` directory and check that the variables make sense for the query.

**Comment by LakshyaKhatri** [comment]
can you provide me a list of datasets that should be tested?
Or can I pick them randomly?

**Comment by juliohm** [comment]
I would produce small queries with ERA5 and other `Product type` in this page: https://cds.climate.copernicus.eu/cdsapp#!/search?type=dataset

**Comment by juliohm** [comment]
@LakshyaKhatri did you figure out the CDS API key on GitHub environments?

**Comment by LakshyaKhatri** [comment]
I found some discussions on how to manage API keys a few days back:
> We can use Julia ENV wrapper to get/set secrets. TwitchTools.jl does this https://github.com/Julia-Streamers/TwitchTools.jl/blob/master/examples/clips.jl

> I'm going with reading the API_KEY from ENV each time its required rather than using a global variable
> ```julia
> function api_key()
>  if haskey(ENV, "API_KEY")
>    return ENV["API_KEY"]
>  else
>    error("Please set API_KEY in your environment")
>  end
> end
> ```

If you can tell me what the end goal is; I will be able to help for sure.

**Comment by juliohm** [comment]
The end goal is to have the Travis CI bot running the tests whenever we push changes to the repository #28.

**Comment by LakshyaKhatri** [comment]
Wow :heart_eyes:, let me search a bit and then I'll open a PR.
