### ISSUE TITLE
Deprecate py2ju in favor of parse

### ISSUE THREAD

**Issue by juliohm** [JuliaClimate/CDSAPI.jl#14]
Now that #6 is fixed we can probably remove `py2ju` and simply reexport the `parse` from JSON.jl:

```julia
using JSON: parse
export parse
```

Also, could you please unexport the `retrieve`? In this case I think it is a good idea to not pollute the namespace and force users to be explict with `CDSAPI.retrieve`.

**Comment by LakshyaKhatri** [comment]
Okay, It's on me.

**Comment by LakshyaKhatri** [comment]
I don't think it'll be a good idea to export JSON.jl's `parse` method since this is an API library, most of the users gonna do a `using JSON` too. In that case, CDSAPI's `parse` method and JSON's `parse` method may conflict.

```julia

julia> using JSON: parse
WARNING: ignoring conflicting import of JSON.parse into Main

```

**Comment by juliohm** [comment]
Oh I think we need to import it so that we export the same methods:

```julia
import JSON: parse
export parse
```

**Comment by LakshyaKhatri** [comment]
Alright, let me try.

**Comment by LakshyaKhatri** [comment]
I forgot about the `Base.parse` method :joy: :facepalm: :

```julia
julia> parse(str)
WARNING: both CDSAPI and Base export "parse"; uses of it in module Main must be qualified
ERROR: UndefVarError: parse not defined
Stacktrace:
 [1] top-level scope at REPL[7]:1
 [2] eval(::Module, ::Any) at ./boot.jl:331
 [3] eval_user_input(::Any, ::REPL.REPLBackend) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:86
 [4] run_backend(::REPL.REPLBackend) at /home/aries/.julia/packages/Revise/BqeJF/src/Revise.jl:1184
 [5] top-level scope at REPL[3]:0
```

**Comment by juliohm** [comment]
Perhaps we should leave it as is then and call it `py2ju` or similar name to avoid these conflicts. It is fine too. I was just trying to avoid another name in the namespace given the minimalist nature of the package.
