### ISSUE TITLE
Bugs in CDSAPI.retrieve

### ISSUE THREAD

**Issue by LakshyaKhatri** [JuliaClimate/CDSAPI.jl#20]
In #15, I pushed some bugs by mistake due to which retrieve stopped working. Kindly merge/provide feedback #19 and #18 so that I can do a rebase and push the corrections

**Comment by juliohm** [comment]
Thank you for checking. I'll do it soon. Finishing breakfast in BRT time. :)

**Comment by juliohm** [comment]
I've merged #19 and can merge #18  as soon as you fix the TAB issue we described there. It would be really nice if we could address #12 before moving forward.

**Comment by LakshyaKhatri** [comment]
I was working on the test cases when I noticed this. Unfortunately this needs to be fixed so that I can write tests for it.
