### ISSUE TITLE
retrieve() throws error if a path is provided instead of filename

### ISSUE THREAD

**Issue by LakshyaKhatri** [JuliaClimate/CDSAPI.jl#23]
this works:
```julia
CDSAPI.retrieve(<some_name>, <some_params>, "<filename>.<extension>")
```
But this throws error:
```julia
CDSAPI.retrieve(<some_name>, <some_params>, "<path_to_file>/<filename>.<extension>")
```

**Comment by juliohm** [comment]
Thank you @LakshyaKhatri for carefully checking it. Could you please address the issue? I'be happy to review.

**Comment by LakshyaKhatri** [comment]
Okay :D

**Comment by LakshyaKhatri** [comment]
The issue is causing due to the use of Julia's `download()`. I can resolve the error, but I think implementing a pure Julian download function will surely give us more control.
Something like this: [Julia download function](https://gist.github.com/oxinabox/3fe139924887c9339de714ce701ba2bc)

**Comment by juliohm** [comment]
Nice @LakshyaKhatri, thanks for the search.

@oxinabox did you have a chance to register that module you shared as a gist somewhere? We are encountering issues with Julia's built-in download as pointed above.

**Comment by oxinabox** [comment]
Yeah, that code now lives in HTTP.jl
As `HTTP.download`

**Comment by juliohm** [comment]
@LakshyaKhatri that is good news :) Can you please try `HTTP.download`?
