### ISSUE TITLE
Return of CDSAPI.retrieve

### ISSUE THREAD

**Issue by juliohm** [JuliaClimate/CDSAPI.jl#24]
I understand that currently the `retrieve` function is returning a dictionary with some keys. Should we document the most relevant keys of this dictionary in the README.md as well?

**Comment by juliohm** [comment]
@michiboo did you have a chance to tackle this issue?

**Comment by michiboo** [comment]
@juliohm  Hi sorry for the late reply, was busy with the hackathon week. I will try create a PR by today!

**Comment by juliohm** [comment]
Thank you @michiboo , merged 👍

**Comment by juliohm** [comment]
Should this information be removed from the README?

```
"request_id"         => "04534ef1-874d-4c81-bb59-9b5effe63e9e"
```

Is it the CDSAPI key you used? If yes, we should remove and leave it as ******

**Comment by juliohm** [comment]
@michiboo coudl you please take a look at this one? Should we erase this information from the README?

**Comment by juliohm** [comment]
@LakshyaKhatri could you please take a look at this one? I will try to run the package locally by the end of the day given that now we have the Travis CI running and everything working. ❤️ We could then register the package and announce it to the community.

**Comment by LakshyaKhatri** [comment]
Hello @juliohm, It's okay to have a request-id in the Readme (it is like a transaction ID that will hold the metadata for our request viz. download size, time, etc.) , but if we have to change it, we can do something like this IMO :smile::
```julia
Dict{String,Any} with 6 entries:
  "result_provided_by" => "8a3eb001-c8e3-4a9c-8170-28191ebea14b"
  "location"           => "http://136.156.133.36/cache-compute-0010/cache/data0/dataset-insitu-glaciers-elevation-mass-8a3eb001a14b.tar.gz"
  "content_type"       => "application/gzip"
  "request_id"         => <request-id>
  "content_length"     => 193660
  "state"              => "completed"
```

**Comment by juliohm** [comment]
I just wanted to confirm that this request ID has nothing to do with the CDSAPI private key :) Thank you for double checking it.

**Comment by michiboo** [comment]
@juliohm  sorry for the late reply! @LakshyaKhatri  Thanks for explaining it! :D
