### ISSUE TITLE
More information while downloading data from CDS

### ISSUE THREAD

**Issue by michiboo** [JuliaClimate/CDSAPI.jl#26]
Ideally it will include the following information:
- [ ] Date and time
- [ ] The file size downloaded
- [ ] Progress bar for downloading
- [ ] Speed for downloading the file

The example below displayed information while downloading from CDS using ECMWF's CDSAPI:
2020-07-06 17:37:01,345 INFO Welcome to the CDS
2020-07-06 17:37:01,345 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-pressure-levels
2020-07-06 17:37:03,596 INFO Request is completed
2020-07-06 17:37:03,597 INFO Downloading http://136.156.133.41/cache-compute-0013/cache/data1/d3adac2-f735-4638-ae0b-3c85684e3848.grib to download.grib (61.4M)
2020-07-06 17:38:05,176 INFO Download rate 1020.9K/s                                                    
Result(content_length=64374600,content_type=application/x-grib,location=http://136.156.133.41/cache-compute-0013/cache/data1/adaptor.mars.internal--1d3adac2-f735-4638-ae0b-3c85684e3848.grib)

**Comment by juliohm** [comment]
I love this idea of showing a more informative progress. Please take a look at the ProgressMeter.jl and the more recent ProgressLogging.jl packages, they can help here.

**Comment by juliohm** [comment]
The new `HTTP.download` provides some progress information already. It is not the cleanest output though. Should we close this issue? I think in order to improve the progress information we would need to submit PRs to HTTP.jl instead.

**Comment by LakshyaKhatri** [comment]
@michiboo,
  - [x] Date and time
  - [x] The file size downloaded
  - [x] Speed for downloading the file

Are covered by #29, so only thing remaining is a progress bar (we have to rewrite `HTTP.download()` if more customization is required )

**Comment by michiboo** [comment]
@juliohm  @LakshyaKhatri  Thanks for the comments! I agreed that this issue should be close!
