### ISSUE TITLE
Configure CI bots for test and coverage

### ISSUE THREAD

**Issue by juliohm** [JuliaClimate/CDSAPI.jl#28]
@Balinus do we have Travis CI and Codecov enabled by default for repositories in the organization? If not, could you please enable it for this repository?

**Comment by LakshyaKhatri** [comment]
Hello @juliohm, is Julia's `ENV` a correct way to manage API keys?

**Comment by LakshyaKhatri** [comment]
or as suggested by Elliot, we can do this: https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

**Comment by juliohm** [comment]
Hi @LakshyaKhatri , since we will be using Travis CI for the automation of tests, maybe we should double check in their documentation the best approach to API keys. I remember for example creating a DOCUMENTER_KEY ins Travis CI for some of my projects as an env variable in their VMs that could be read during test time. Could you please double check Travis docs to see what is the recommended method?

**Comment by juliohm** [comment]
@Balinus did you have a chance to take a look into this? Anyone else from JuliaClimate with admin permissions could double check the Travis CI + Codecov setup in this repo?

**Comment by juliohm** [comment]
I was able to activate the Travis CI for this repo @LakshyaKhatri , will add the badges to the README.

**Comment by LakshyaKhatri** [comment]
@juliohm, I might not be able to contribute much this week because of a hackathon! I will continue my contributions after the hackathon completion.

**Comment by juliohm** [comment]
Thank you @LakshyaKhatri for the heads up, have fun in the hackaton!

**Comment by juliohm** [comment]
The badges are in the README and the builds are being triggered. Now we need to fix the tests. Will open a separate issue.
