### ISSUE TITLE
reduce screen output and less polling on the server

### ISSUE THREAD

**Issue by Alexander-Barth** [JuliaClimate/CDSAPI.jl#40]
Thank you for make this very nice package available. I think it will be very useful for my research and my students :-)

When I made my first request to the CDI API, I see this message
`request queue status queued` repeatedly (about 5 or 10 messages per seconds).

It seems that the API is constantly polling the server about the status:
https://github.com/JuliaClimate/CDSAPI.jl/blob/master/src/CDSAPI.jl#L39

I am wondering if it is not better to add some sleep time as in the python API:
https://github.com/ecmwf/cdsapi/blob/master/cdsapi/api.py#L479-L482

(which increases by 1.5 every time starting from 1 s until it reaches the maximum 2 minutes)

I can make a PR if it is helpful :-) Maybe we can also update to HTTP 1.0 ?

For reference this is the request I am running:

```julia
using CDSAPI

req = Dict("class" => "ea",
     "expver" => "1",
     "dataset" => "interim",
     "date" => "2018-12-01/to/2018-12-05",
     "levtype" => "sfc",
     "grid" => "0.75/0.75",
     "param" => "146.128/147.128/151.128/164.128/165.128/166.128/167.128/168.128/175.128/176.128/177.128/180.128/181.128/182.128/205.128/228.128/34.128/58.128",
     "step" => "3/6/9/12",
     "stream" => "oper",
     "target" => "output",
     "time" => "00:00:00/12:00:00",
     "type" => "fc",
     "area" => "41.875/7.5/44.625/12.375",
     "format" => "netcdf")

CDSAPI.retrieve("reanalysis-era5-complete", req, "output")
```

**Comment by michiboo** [comment]
@Alexander-Barth  Hello thanks for the suggestion! feel free to make a PR! improvement is always welcome! :)

**Comment by juliohm** [comment]
Fixed on master. Thank you @Alexander-Barth !

**Comment by Alexander-Barth** [comment]
Thanks @juliohm for merging the PR :-)

**Comment by juliohm** [comment]
Thank you Alex for the suggested improvment. A PR is very welcome :)

Em sex., 8 de jul. de 2022 06:02, Alexander Barth ***@***.***>
escreveu:
