### ISSUE TITLE
CDSAPI indexing error

### ISSUE THREAD

**Issue by deszoeke** [JuliaClimate/CDSAPI.jl#51]
```
CDSAPI.retrieve("reanalysis-era5-pressure-levels",
                  CDSAPI.py2ju("""
                  {
                      'product_type': 'reanalysis',
                      'format': 'netcdf',
                      'area': [30, 40, -4, 90],
                      'time': '00:00',
                      'month': '07',
                      'day': [ '01', '02'],
                      'year': ['2018', '2019', '2020', '2021', '2022'],
                      'pressure_level': [ '850', '1000'],
                      'variable': ['divergence', 'fraction_of_cloud_cover', 'geopotential',
                          'potential_vorticity', 'specific_humidity', 'temperature',
                          'u_component_of_wind', 'v_component_of_wind', 'vertical_velocity',
                          'vorticity'],
                  }
                  """),
                  "download.nc")
ERROR: BoundsError: attempt to access 1-element Vector{SubString{String}} at index [2]
Stacktrace:
 [1] getindex
   @ ./array.jl:924 [inlined]
 [2] indexed_iterate
   @ ./tuple.jl:89 [inlined]
 [3] (::CDSAPI.var"#2#3"{Dict{Any, Any}})(f::IOStream)
   @ CDSAPI ~/.julia/packages/CDSAPI/QDaMg/src/CDSAPI.jl:21
 [4] open(f::CDSAPI.var"#2#3"{Dict{Any, Any}}, args::String; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Base ./io.jl:384
 [5] open
   @ ./io.jl:381 [inlined]
 [6] retrieve(name::String, params::Dict{String, Any}, filename::String; max_sleep::Float64)
   @ CDSAPI ~/.julia/packages/CDSAPI/QDaMg/src/CDSAPI.jl:19
 [7] retrieve(name::String, params::Dict{String, Any}, filename::String)
   @ CDSAPI ~/.julia/packages/CDSAPI/QDaMg/src/CDSAPI.jl:17
 [8] top-level scope
   @ REPL[31]:1
```

The Get API button has vectors in the Dict with trailing commas. They don't seem to make any difference.
 
This error is achieved by the example in the README also.

```
julia> versioninfo()
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: 8 × Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores
```

**Comment by deszoeke** [comment]
After sending this, Googling turned up some different ways of formatting the contents of ~/.cdsapirc. I will investigate further. It might be brittle if Python cdsapi changes and then expects a different format than julia CDSAPI. I can’t tell what substring parsing has gone amiss.


On Mar 28, 2023, at 11:01 AM, Júlio Hoffimann ***@***.***> wrote:

﻿

[This email originated from outside of OSU. Use caution with links and attachments.]

@LakshyaKhatri<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLakshyaKhatri&data=05%7C01%7Csimon.deszoeke%40oregonstate.edu%7C1ca17c31372a4b7c834508db2fb66f11%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C638156232835060135%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3ZuSKY9IcwZ7u%2Bz%2FMWmfufzrtNhO%2FedmjgLsx3Sp4oA%3D&reserved=0> can you take a look at this? We didn't touch this code in a while, don't know if something changed in the CDS API that we are consuming.

**Comment by LakshyaKhatri** [comment]
Hi there! 👋🏻
Will check on my end 🤔

**Comment by deszoeke** [comment]
The trailing empty line in `~./cdsapirc` is responsible for the particular julia CDSAPI error above.

The request works and saves data locally when the trailing line is removed.
